Vagrant.configure("2") do |config|
  config.vm.box = "generic/rocky9"

  # Set up a private network for host-VM communication
  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.network "forwarded_port", guest: 80, host: 8080

  # Sync a local folder to the VM
  config.vm.synced_folder "./data", "/vagrant_data"

  # Provider configuration for libvirt
  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 1024
    libvirt.cpus = 1
  end

  # Simple provisioning example
  config.vm.provision "shell", inline: <<-SHELL
    sudo dnf update -y
    sudo dnf install nginx -y
    sudo firewall-cmd --zone=public --add-port=80/tcp --permanent
    sudo firewall-cmd --reload
    
    sudo mkdir -p /var/www/html/app.example.com
    sudo cp -r /vagrant_data/* /var/www/html/app.example.com/
    sudo chown -R nginx:nginx /var/www/html/app.example.com
    sudo restorecon -R /var/www/html/app.example.com

    sudo systemctl enable --now nginx
    sudo systemctl start nginx
    sudo cp /vagrant_data/app.example.com.conf /etc/nginx/conf.d/app.example.com.conf
    sudo nginx -t
    sudo systemctl reload nginx
    
  SHELL
end